---
- name: Install nftables service
  yum:
    name: nftables
    state: latest
  when: ansible_facts.services['nftables.service'] is undefined
  tags:
    - nftables

- name: Disable firewalld and enable NFtables
  block:
    - name: Stop and mask firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no
        masked: yes

    - name: Enable service nftables and ensure it is not masked
      systemd:
        name: nftables
        state: started
        enabled: yes
        masked: no
      register: result_activate_nftables
  when: (activate_firewall | bool == true) and (activate_firewall is defined)
  tags:
    - nftables 

- name: Enable the custom rules
  lineinfile:
    path: /etc/sysconfig/nftables.conf
    line: 'include "/etc/nftables/custome-ruleset.nft"'
  tags:
    - nftables

- name: Copy the custom rules template file
  template:
    src: custom_ruleset.j2
    dest: /etc/nftables/custome-ruleset.nft
    owner: root
    group: root
    mode: '0755'
  register: result_change_rules
  tags:
    - nftables

- gebug:
    var: result_activate_nftables

- gebug:
    var: result_change_rules

#- name: Reload rules
#  notify: Restart_NFT
...