---
- name: Install nftables service
  yum:
    name: nftables
    state: latest
  when: ansible_facts.services['nftables.service'] is undefined

- name: Disable firewalld and enable NFtables
  block:
    - name: Stop and mask firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no
        masked: yes

    - name: Enable service nftables and ensure it is not masked
      systemd:
        name: nftables
        state: started
        enabled: yes
        masked: no
      register: result_activate_nftables
  when: (activate_firewall | bool == true) and (activate_firewall is defined)

- name: Disable prevent Docker from manipulating iptables
  block:
    - name: Copy the Docker engine’s configuration file
      copy:
        src: files/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0600
      register: copy_config

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
      when: copy_config is succeeded and ((restart_docker_srv | bool == true) and (restart_docker_srv is defined))
  when: ansible_facts.services['docker.service'] is defined and ansible_facts.services['docker.service'].status == 'enabled'

- name: Enable the custom rules
  lineinfile:
    path: /etc/sysconfig/nftables.conf
    line: 'include "/etc/nftables/custome-ruleset.nft"'

- name: Copy the custom rules template file
  template:
    src: custom_ruleset.j2
    dest: /etc/nftables/custome-ruleset.nft
    owner: root
    group: root
    mode: '0755'
  register: result_change_rules
...