site_name: Configuration RHEL/CentOS
site_description: "Настройка сервера на базе OC RHEL/CentOS"
copyright: Copyright &copy; <a href="https://github.com/D34m0nN0n3">Dmitriy Prigoda</a>.

repo_name: "ansible-ssr-os"
repo_url: "https://github.com/D34m0nN0n3/ansible-ssr-os"

use_directory_urls: false

nav:
    - Общее описание: 'index.md'
    - Как применять:
      - Используя `bootstrap` хост: 'ansible/engine.md'
      - Используя RH Satellite/Katello: 'ansible/satellite.md'
    - Роли:
      - Auditd: 'roles/auditd.md'
      - Cockpit: 'roles/cockpit.md'
      - Firewall: 'roles/firewall.md'
      - NTPclient: 'roles/ntpclient.md'
      - SELinux: 'roles/selinux.md'
      - SSHD: 'roles/sshd.md'
      - Sysconfig: 'roles/sysconfig.md'
      - Users account: 'roles/users.md'
      - ITMA: 'roles/itma.md'
      - NetBackup: 'roles/netbackup.md'
      - MPuser: 'roles/mpuser.md'
    - Дополнительные материалы: 'seealso.md'

plugins:
    - search
    - pdf-export:
        verbose: true
        media_type: print
        combined: true
        combined_output_path: pdf/combined.pdf
        theme_handler_path: theme-handler/material.py

theme:
  name: material
  custom_dir: 'material'
  palette:
    scheme: default
    primary: blue grey
    accent: red
  logo: 'assets/img/logo/logo.svg'
  favicon: 'assets/img/favicon/favicon.ico'
  language: 'ru'
  feature:
    tabs: false

extra:
  search:
    language: 'ru, en'

extra_css:
  - material/assets/css/main.css
  - material/assets/libs/magnific-popup/magnific-popup.css
  - material/assets/css/pdf.css

extra_javascript:
  - material/assets/libs/jquery/jquery-3.4.0.min.js
  - material/assets/libs/magnific-popup/jquery.magnific-popup.min.js
  - material/assets/js/main.js

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_blockdiag:
      format: svg
  - markdown_include.include
