site_name: TeX Docs
site_description: "Documentation for TeX Docs site"
copyright: Copyright &copy; <a href="https://github.com/D34m0nN0n3">Dmitriy Prigoda</a>.

repo_name: "ansible-ssr-texdocs"
repo_url: "https://github.com/D34m0nN0n3/ansible-ssr-texdocs"

use_directory_urls: false

nav:
    - Общее описание: 'index.md'
    - Дополнительные материалы: 'seealso.md'

plugins:
    - search
    - pdf-export:
        verbose: true
        media_type: print
        combined: true
        combined_output_path: pdf/combined.pdf
        theme_handler_path: theme-handler/material.py

theme:
  name: material
  custom_dir: 'material'
  palette:
    scheme: default
    primary: blue grey
    accent: red
  logo: 'assets/img/logo/logo.svg'
  favicon: 'assets/img/favicon/favicon.ico'
  language: 'ru'
  feature:
    tabs: false

extra:
  search:
    language: 'ru, en'

extra_css:
  - material/assets/css/main.css
  - material/assets/libs/magnific-popup/magnific-popup.css

extra_javascript:
  - material/assets/libs/jquery/jquery-3.4.0.min.js
  - material/assets/libs/magnific-popup/jquery.magnific-popup.min.js
  - material/assets/js/main.js

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed

