---
- name: Restart IPT
  shell: /usr/sbin/iptcfg init
  args:
    executable: /bin/bash
  when: ((activate_firewall | bool == true) and (activate_firewall is defined))

- name: Restart NFT
  systemd:
    name: nftables
    state: restarted
  when: ((activate_firewall | bool == true) and (activate_firewall is defined))
