---
- name: Auditd restart service
  command: "service auditd restart"
  environment:
    PATH: '/usr/sbin:/usr/bin:/sbin:/bin'
  args:
    warn: False
  when: >
    (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7)
