---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible:latest
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    command: "/usr/sbin/init"
  - name: centos8
    image: geerlingguy/docker-centos8-ansible:latest
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    command: "/usr/sbin/init"
#  - name: centos8
#    image: nexus.rzd/rzdbaseimages/molecule-systemd-centos:8.001
#    pre_build_image: true
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    capabilities:
#      - SYS_ADMIN
#    command: "/usr/sbin/init"
#  - name: centos7
#    image: nexus.rzd/rzdbaseimages/molecule-systemd-centos:7.001
#    pre_build_image: true
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    capabilities:
#      - SYS_ADMIN
#    command: "/usr/sbin/init"
provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
    ANSIBLE_ROLES_PATH: $ephemeral_directory/roles/:$project_directory/roles/:$project_directory/../:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
...