---
# For hots in SPD
intranet: true
nf_int: true
# For ports
nf_ports: {}
# For rules
nf_custom_ruleset: {}
# Limit connections per source IP
sper_limit_conn: '1024'
# The Docker need restart
restart_docker_srv: false
