---
- name: Check if chronyd service exists
  stat: path="/usr/lib/systemd/system/chronyd.service"
  register: chronyd_service_status
  tags:
    - enable_chronyd
- block:
  - name: Install chronyd service
    yum:
      name: chrony
      state: latest
    
  - name: Enable service chronyd and ensure it is not masked
    systemd:
      name: chronyd
      enabled: yes
      masked: no
  when: chronyd_service_status.stat.exists == False

- name: Copy the chrony.conf template file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: sync_ntp
